### ISSUE TITLE
multi-thread read support

### ISSUE THREAD

**Issue by chenliangomc** [biocommons/biocommons.seqrepo#11]
When the HGVS function(s) are called in a multithreading programs (eg., webapp based on Django), the calls are failed with exception:

ProgrammingError('SQLite objects created in a thread can only be used in that same thread.The object was created in thread id {foo} and this is thread id {bar}',)

seealso: https://groups.google.com/forum/#!topic/hgvs-discuss/MeHe7jtRIPo

**Comment by reece** [comment]
@chenliangomc, @keithcallenberg:

Both of you have reported issues with hgvs + seqrepo multithreading. I cannot reproduce the issue. Would you please try the following script and post your results on this issue?

https://github.com/biocommons/biocommons.seqrepo/blob/master/misc/threading-verification.py


My results:
```
sys.platform: linux2
sys.version: 2.7.13 (default, Jan 19 2017, 14:48:08)  [GCC 6.3.0 20170118]
sqlite3.sqlite_version: 3.16.2
pid 9659 created SeqRepo(root_dir=/tmp/sr, writeable=False)
(9660, 9659, 'SMELLASSWEET')
pid 9659 created SeqRepo(root_dir=/tmp/sr, writeable=True)
(9662, 9659, 'SMELLASSWEET')
```

**Comment by keithcallenberg** [comment]
@reece I've shifted gears onto a different project right now so I don't have an environment easily available to test with. @chenliangomc would you be able to test this out?

**Comment by jamespeacock** [comment]
Hi @reece I have been trying to run the threading-verification.py script that you provided but run into either a KeyError for the alias or a database locked error.

When creating seqrepo object with writeable=False

```sys.platform: linux
sys.version: 3.6.6 (default, Oct 17 2018, 15:38:40)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
sqlite3.sqlite_version: 3.18.0
FabgzWriter(/tmp/sr/sequences/2019/0114/2354/1547510044.438359.fa.bgz) was not explicitly closed; may result in lost data
pid 443 created SeqRepo(root_dir=/tmp/sr, writeable=False)
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "test_sqlite.py", line 38, in fetch_seq
    q.put((pid, ppid, sr[nsa]))
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/seqrepo.py", line 70, in __getitem__
    return self.fetch(alias=a, namespace=ns)
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/seqrepo.py", line 96, in fetch
    seq_id = self._get_unique_seqid(alias=alias, namespace=namespace)
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/seqrepo.py", line 215, in _get_unique_seqid
    raise KeyError("Alias {} (namespace: {})".format(alias, namespace))
KeyError: 'Alias en (namespace: rose)'```

And when creating a seqrepo object with writeable=True

```[root@c189e396c7c4 misc]# python threading-verification.py
sys.platform: linux
sys.version: 3.6.6 (default, Oct 17 2018, 15:38:40)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
sqlite3.sqlite_version: 3.18.0
pid 469 created SeqRepo(root_dir=/tmp/sr, writeable=True)
Fetching from file opened for writing;
            closing first (2019/0115/0002/1547510545.3114693.fa.bgz)
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "threading-verification.py", line 39, in fetch_seq
    q.put((pid, ppid, sr[nsa]))
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/seqrepo.py", line 70, in __getitem__
    return self.fetch(alias=a, namespace=ns)
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/seqrepo.py", line 97, in fetch
    return self.sequences.fetch(seq_id, start, end)
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 114, in fetch
    self.commit()
  File "/usr/local/lib/python3.6/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 99, in commit
    self._db.commit()
sqlite3.OperationalError: database is locked```

**Comment by reece** [comment]
Thanks @chenliangomc. I'll investigate.
