### ISSUE TITLE
OSError: Unable to open SeqRepo directory /projects00/tmp/usr/hgvs/bin/seqrepo/latest

### ISSUE THREAD

**Issue by ypchan** [biocommons/biocommons.seqrepo#72]
## bash code and error
`
SEQREPO_ROOT=/projects00/tmp/usr/hgvs/bin/seqrepo

mkdir $SEQREPO_ROOT 

seqrepo --root-directory $SEQREPO_ROOT init

seqrepo --root-directory $SEQREPO_ROOT load --namespace dog Can.fna

seqrepo --root-directory $SEQREPO_ROOT show-status

Traceback (most recent call last):
  File "/psd/biosoft/anaconda/envs/Python-3.7/bin/seqrepo", line 10, in <module>
    sys.exit(main())
  File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/biocommons/seqrepo/cli.py", line 545, in main
    opts.func(opts)
  File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/biocommons/seqrepo/cli.py", line 420, in show_status
    sr = SeqRepo(seqrepo_dir)
  File "/psd/biosoft/anaconda/envs/Python-3.7/lib/python3.7/site-packages/biocommons/seqrepo/seqrepo.py", line 56, in __init__
    raise OSError("Unable to open SeqRepo directory {}".format(self._root_dir))
OSError: Unable to open SeqRepo directory /projects00/tmp/usr/hgvs/bin/seqrepo/latest
`

Hello, sir,
when I used seqrepo to build a local seqrepo, a OSError error happened. 
Although I fixed the problem by doing this:

`#ap.add_argument("--instance-name", "-i", default=DEFAULT_INSTANCE_NAME_RO, help="instance name")

#modifed the default
ap.add_argument("--instance-name", "-i", default=DEFAULT_INSTANCE_NAME_RW, help="instance name")

`
I hope you fix this error in future change.
Anyway， thank you for your great program.

**Comment by reece** [comment]
This command is working as intended, although I agree that the RO/RW split across subcommands is very confusing.

The interface is likely to change in the next several months in order to accommodate new features. The issue you raise provides additional incentive to do that soon. Thanks!
