### ISSUE TITLE
Empty description in setup

### ISSUE THREAD

**Issue by ok-gitr** [biocommons/biocommons.seqrepo#95]
Hi, 

I am using `conda skeleton` to build a conda package for the latest release on [pypi](https://pypi.org/project/biocommons.seqrepo/0.6.3/) and I am getting an error which i think is caused by an empty [description](https://github.com/biocommons/biocommons.seqrepo/blame/main/setup.cfg#L10). Can this be fixed? 

Thanks

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_skeleton.py", line 60, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 317, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 755, in get_package_metadata
    metadata["summary"] = get_summary(pkginfo)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 904, in get_summary
    return pkginfo.get("summary", "Summary of the package").replace('"', r'\"')
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by reece** [comment]
Thanks for the prod. This change was made to main. Please confirm and close issue if resolved.

**Comment by ok-gitr** [comment]
It does not look like the change is reflected on pypi yet.

**Comment by reece** [comment]
I just updated and see the description at https://pypi.org/project/biocommons.seqrepo/. Does that solve the problem?

**Comment by ok-gitr** [comment]
that solves it! thanks for looking into it.
